# Site settings
title: Anthony J. Ellis
email: ajellis1989@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Follow my journey, as I dive into the ocean of web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ajellis.github.io" # the base hostname & protocol for your site
twitter_username: ajellis1989
github_username:  ajellis

# Build settings
markdown: kramdown
permalink: /blog/:title/
pages_list:
  About: '/about'
  Archive: '/archive'



exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vend
